"""
HTML 报告生成器 - 使用 Tailwind CSS 和 CDN 图标
"""
from typing import Dict, Any, Optional
from datetime import datetime
from pathlib import Path


class HTMLReporter:
    """HTML 报告生成器"""

    def __init__(self, use_cdn: bool = True, language: str = 'zh_CN'):
        """
        初始化报告生成器

        Args:
            use_cdn: 是否使用 CDN (默认 True)
            language: 语言代码 (zh_CN, en_US)
        """
        self.use_cdn = use_cdn
        self.language = language

        # 加载翻译
        self._translations = self._load_translations()

    def _load_translations(self) -> Dict[str, str]:
        """加载翻译"""
        translations = {
            'zh_CN': {
                'title': 'Skill 安全扫描报告',
                'generated': '生成时间',
                'scanned_paths': '扫描路径',
                'scan_summary': '扫描摘要',
                'total_files': '文件总数',
                'total_issues': '问题总数',
                'filter': '筛选',
                'all': '全部',
                'recommendation': '建议',
                'location': '位置',
                'detected_pattern': '检测到的模式',
                'confidence': '置信度',
                'issues': '问题',
                'and_more': '还有 ... 个',
                'generated_by': '生成工具',
                'do_not_use': '请勿使用 - 检测到严重安全风险',
                'not_recommended': '不推荐使用 - 检测到高风险问题',
                'review_needed': '需要审查 - 请人工审查后使用',
                'use_with_caution': '谨慎使用 - 存在轻微风险',
                'safe': '安全 - 未检测到明显安全问题'
            },
            'en_US': {
                'title': 'Skill Security Scan Report',
                'generated': 'Generated',
                'scanned_paths': 'Scanned Paths',
                'scan_summary': 'Scan Summary',
                'total_files': 'Total Files',
                'total_issues': 'Total Issues',
                'filter': 'Filter',
                'all': 'All',
                'recommendation': 'Recommendation',
                'location': 'Location',
                'detected_pattern': 'Detected Pattern',
                'confidence': 'Confidence',
                'issues': 'Issues',
                'and_more': 'and ... more',
                'generated_by': 'Generated by',
                'do_not_use': 'DO NOT USE THIS SKILL - Critical security risks detected',
                'not_recommended': 'NOT RECOMMENDED - High-risk issues detected',
                'review_needed': 'REVIEW NEEDED - Manual review required before use',
                'use_with_caution': 'USE WITH CAUTION - Minor risks detected',
                'safe': 'SAFE - No obvious security issues detected'
            }
        }
        return translations.get(self.language, translations['zh_CN'])

    def _t(self, key: str) -> str:
        """获取翻译文本"""
        return self._translations.get(key, key)

    def generate(self, report: Dict[str, Any]) -> str:
        """
        生成 HTML 报告

        Args:
            report: 扫描报告

        Returns:
            str: HTML 内容
        """
        # 获取扫描时间
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        # 构建风险评估颜色和图标
        risk_level = report.get('risk_level', 'UNKNOWN')
        risk_score = report.get('risk_score', 0)
        risk_config = self._get_risk_config(risk_level)

        # 按严重级别分组
        findings_by_severity = self._group_by_severity(report.get('findings', []))

        # 获取自定义 CSS
        custom_css = self._get_custom_css()

        # 生成 HTML
        html = f"""<!DOCTYPE html>
<html lang="{self.language}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self._t('title')}</title>
    {self._get_tailwind_cdn()}
    {self._get_font_awesome_cdn()}
    <style>
        {custom_css}
    </style>
</head>
<body class="bg-gray-50">
    <div class="min-h-screen">
        <!-- Header -->
        <header class="bg-gradient-to-r {risk_config['gradient']} text-white shadow-lg">
            <div class="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
                <div class="flex items-center justify-between">
                    <div>
                        <h1 class="text-3xl font-bold flex items-center">
                            <i class="fas fa-shield-alt mr-3"></i>
                            {self._t('title')}
                        </h1>
                        <p class="mt-2 text-white/80">
                            <i class="far fa-clock mr-1"></i>
                            {self._t('generated')}: {timestamp}
                        </p>
                    </div>
                    <div class="text-right">
                        <div class="text-6xl font-bold">{risk_score:.1f}</div>
                        <div class="text-xl">{risk_level}</div>
                    </div>
                </div>
            </div>
        </header>

        <!-- Main Content -->
        <main class="max-w-7xl mx-auto px-4 py-8 sm:px-6 lg:px-8">
            <!-- Scanned Paths -->
            {self._render_paths_section(report)}

            <!-- Summary Cards -->
            {self._render_summary_section(report, risk_config)}

            <!-- Filter Controls -->
            {self._render_filter_controls(findings_by_severity)}

            <!-- Findings -->
            {self._render_findings_section(findings_by_severity)}

            <!-- Recommendation -->
            {self._render_recommendation_section(risk_level, risk_config)}
        </main>

        <!-- Footer -->
        <footer class="bg-white border-t mt-12">
            <div class="max-w-7xl mx-auto px-4 py-6 sm:px-6 lg:px-8">
                <p class="text-center text-gray-500 text-sm">
                    <i class="fas fa-code mr-1"></i>
                    {self._t('generated_by')} skill-security-scan v1.0.0
                </p>
            </div>
        </footer>
    </div>

    {self._get_interactive_script()}
</body>
</html>"""
        return html

    def _get_risk_config(self, level: str) -> Dict[str, str]:
        """获取风险级别配置"""
        configs = {
            'CRITICAL': {
                'color': 'red',
                'bg_color': 'bg-red-500',
                'text_color': 'text-red-600',
                'border_color': 'border-red-500',
                'icon': 'fa-exclamation-triangle',
                'gradient': 'from-red-600 to-red-800',
                'bg_light': 'bg-red-50'
            },
            'HIGH': {
                'color': 'orange',
                'bg_color': 'bg-orange-500',
                'text_color': 'text-orange-600',
                'border_color': 'border-orange-500',
                'icon': 'fa-exclamation-circle',
                'gradient': 'from-orange-500 to-orange-700',
                'bg_light': 'bg-orange-50'
            },
            'MEDIUM': {
                'color': 'yellow',
                'bg_color': 'bg-yellow-500',
                'text_color': 'text-yellow-600',
                'border_color': 'border-yellow-500',
                'icon': 'fa-exclamation',
                'gradient': 'from-yellow-500 to-yellow-700',
                'bg_light': 'bg-yellow-50'
            },
            'LOW': {
                'color': 'blue',
                'bg_color': 'bg-blue-500',
                'text_color': 'text-blue-600',
                'border_color': 'border-blue-500',
                'icon': 'fa-info-circle',
                'gradient': 'from-blue-500 to-blue-700',
                'bg_light': 'bg-blue-50'
            },
            'SAFE': {
                'color': 'green',
                'bg_color': 'bg-green-500',
                'text_color': 'text-green-600',
                'border_color': 'border-green-500',
                'icon': 'fa-check-circle',
                'gradient': 'from-green-500 to-green-700',
                'bg_light': 'bg-green-50'
            }
        }
        return configs.get(level, configs['SAFE'])

    def _get_tailwind_cdn(self) -> str:
        """获取 Tailwind CSS CDN"""
        if self.use_cdn:
            return '<script src="https://cdn.tailwindcss.com"></script>'
        return ''

    def _get_font_awesome_cdn(self) -> str:
        """获取 Font Awesome CDN"""
        if self.use_cdn:
            return '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">'
        return ''

    def _get_custom_css(self) -> str:
        """获取自定义 CSS"""
        return """
        .finding-card {
            transition: all 0.3s ease;
        }
        .finding-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1);
        }
        .severity-badge {
            animation: pulse 2s infinite;
        }
        @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.7; }
        }
        .collapsible-content {
            max-height: 0;
            overflow: hidden;
            transition: max-height 0.3s ease-out;
        }
        .collapsible-content.expanded {
            max-height: 1000px;
        }
        .code-block {
            background: #1f2937;
            color: #f3f4f6;
            border-radius: 0.375rem;
            padding: 0.75rem;
            font-family: 'Courier New', monospace;
            font-size: 0.875rem;
            overflow-x: auto;
        }
        """

    def _render_paths_section(self, report: Dict[str, Any]) -> str:
        """渲染扫描路径部分"""
        if 'scanned_paths' in report and report['scanned_paths']:
            paths_html = ""
            for path in report['scanned_paths']:
                paths_html += f"""
                <div class="flex items-center text-gray-700">
                    <i class="fas fa-folder text-yellow-500 mr-2"></i>
                    <code class="bg-gray-100 px-2 py-1 rounded text-sm">{path}</code>
                </div>
                """
            return f"""
            <div class="bg-white rounded-lg shadow p-6 mb-6">
                <h2 class="text-xl font-semibold text-gray-800 mb-4 flex items-center">
                    <i class="fas fa-map-marker-alt text-blue-500 mr-2"></i>
                    {self._t('scanned_paths')} ({len(report['scanned_paths'])})
                </h2>
                <div class="space-y-2">
                    {paths_html}
                </div>
            </div>
            """
        return ""

    def _render_summary_section(self, report: Dict[str, Any], risk_config: Dict[str, str]) -> str:
        """渲染摘要部分"""
        summary = report.get('summary', {})
        total_files = report.get('total_files', 0)

        cards_html = f"""
        <div class="bg-white rounded-lg shadow p-6">
            <div class="flex items-center justify-between mb-4">
                <h2 class="text-xl font-semibold text-gray-800">
                    <i class="fas fa-chart-pie text-purple-500 mr-2"></i>
                    {self._t('scan_summary')}
                </h2>
                <span class="{risk_config['bg_color']} text-white px-3 py-1 rounded-full text-sm font-semibold">
                    <i class="fas fa-flag mr-1"></i>
                    {report.get('risk_level', 'UNKNOWN')}
                </span>
            </div>

            <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
                <!-- Total Files -->
                <div class="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-4">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-blue-600 font-medium">{self._t('total_files')}</p>
                            <p class="text-2xl font-bold text-blue-700">{total_files}</p>
                        </div>
                        <i class="fas fa-file-alt text-3xl text-blue-300"></i>
                    </div>
                </div>

                <!-- Critical -->
                <div class="bg-gradient-to-br from-red-50 to-red-100 rounded-lg p-4">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-red-600 font-medium">Critical</p>
                            <p class="text-2xl font-bold text-red-700">{summary.get('CRITICAL', 0)}</p>
                        </div>
                        <i class="fas fa-exclamation-triangle text-3xl text-red-300"></i>
                    </div>
                </div>

                <!-- Warning -->
                <div class="bg-gradient-to-br from-yellow-50 to-yellow-100 rounded-lg p-4">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-yellow-600 font-medium">Warning</p>
                            <p class="text-2xl font-bold text-yellow-700">{summary.get('WARNING', 0)}</p>
                        </div>
                        <i class="fas fa-exclamation-circle text-3xl text-yellow-300"></i>
                    </div>
                </div>

                <!-- Info -->
                <div class="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-4">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-sm text-blue-600 font-medium">Info</p>
                            <p class="text-2xl font-bold text-blue-700">{summary.get('INFO', 0)}</p>
                        </div>
                        <i class="fas fa-info-circle text-3xl text-blue-300"></i>
                    </div>
                </div>
            </div>

            <div class="mt-4 p-4 bg-gray-50 rounded-lg">
                <div class="flex items-center justify-between">
                    <span class="text-gray-600">{self._t('total_issues')}</span>
                    <span class="text-2xl font-bold {risk_config['text_color']}">{report.get('total_issues', 0)}</span>
                </div>
            </div>
        </div>
        """
        return cards_html

    def _render_filter_controls(self, findings_by_severity: Dict[str, list]) -> str:
        """渲染过滤器控制"""
        total_counts = {}
        for severity, findings in findings_by_severity.items():
            total_counts[severity] = len(findings)

        return f"""
        <div class="bg-white rounded-lg shadow p-6 mb-6">
            <div class="flex flex-wrap items-center gap-3">
                <span class="text-gray-700 font-medium">{self._t('filter')}:</span>
                <button onclick="filterFindings('all')" class="filter-btn px-4 py-2 rounded-lg bg-gray-200 hover:bg-gray-300 transition-colors">
                    <i class="fas fa-list mr-1"></i>{self._t('all')}
                </button>
                <button onclick="filterFindings('CRITICAL')" class="filter-btn px-4 py-2 rounded-lg bg-red-100 text-red-700 hover:bg-red-200 transition-colors">
                    <i class="fas fa-exclamation-triangle mr-1"></i>Critical ({total_counts.get('CRITICAL', 0)})
                </button>
                <button onclick="filterFindings('WARNING')" class="filter-btn px-4 py-2 rounded-lg bg-yellow-100 text-yellow-700 hover:bg-yellow-200 transition-colors">
                    <i class="fas fa-exclamation-circle mr-1"></i>Warning ({total_counts.get('WARNING', 0)})
                </button>
                <button onclick="filterFindings('INFO')" class="filter-btn px-4 py-2 rounded-lg bg-blue-100 text-blue-700 hover:bg-blue-200 transition-colors">
                    <i class="fas fa-info-circle mr-1"></i>Info ({total_counts.get('INFO', 0)})
                </button>
            </div>
        </div>
        """

    def _render_findings_section(self, findings_by_severity: Dict[str, list]) -> str:
        """渲染发现部分"""
        severity_order = ['CRITICAL', 'WARNING', 'INFO']
        sections = []

        for severity in severity_order:
            if severity not in findings_by_severity or not findings_by_severity[severity]:
                continue

            findings = findings_by_severity[severity]
            config = self._get_risk_config(severity)

            findings_html = ""
            for i, finding in enumerate(findings[:50]):  # 限制显示数量
                findings_html += self._render_finding_card(finding, config, i)

            sections.append(f"""
            <div class="finding-section mb-8" data-severity="{severity}">
                <h3 class="text-2xl font-bold {config['text_color']} mb-4 flex items-center">
                    <i class="fas {config['icon']} mr-2"></i>
                    {severity} {self._t('issues')} ({len(findings)})
                </h3>
                <div class="space-y-4">
                    {findings_html}
                </div>
                {"" if len(findings) <= 50 else f'<p class="text-gray-500 mt-4">... {self._t("and_more")} {len(findings) - 50}</p>'}
            </div>
            """)

        return '\n'.join(sections)

    def _render_finding_card(self, finding: Dict[str, Any], config: Dict[str, str], index: int) -> str:
        """渲染单个发现卡片"""
        rule_id = finding.get('rule_id', 'UNKNOWN')
        file = finding.get('file', 'Unknown')
        line = finding.get('line', 0)
        pattern = finding.get('pattern', '')
        description = finding.get('description', '')
        confidence = finding.get('confidence', 0)

        confidence_label = self._get_confidence_label(confidence)
        confidence_class = self._get_confidence_color(confidence)

        return f"""
        <div class="finding-card bg-white rounded-lg shadow-md border-l-4 {config['border_color']} overflow-hidden">
            <div class="p-6">
                <div class="flex items-start justify-between mb-3">
                    <div class="flex-1">
                        <div class="flex items-center gap-3 mb-2">
                            <span class="{config['bg_color']} text-white px-3 py-1 rounded-full text-sm font-semibold">
                                {rule_id}
                            </span>
                            <span class="{confidence_class} px-3 py-1 rounded-full text-sm font-medium">
                                <i class="fas fa-chart-line mr-1"></i>
                                {confidence_label} {self._t('confidence')}
                            </span>
                        </div>
                        <p class="text-gray-600 mb-2">{description}</p>
                    </div>
                    <button onclick="toggleCollapse({index})" class="text-gray-400 hover:text-gray-600">
                        <i class="fas fa-chevron-down" id="icon-{index}"></i>
                    </button>
                </div>

                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-3 text-sm">
                    <div class="flex items-center text-gray-600">
                        <i class="fas fa-file-code mr-2 text-blue-500"></i>
                        <span class="font-medium">{self._t('location')}:</span>
                        <code class="ml-2 bg-gray-100 px-2 py-1 rounded text-xs">{file}:{line}</code>
                    </div>
                </div>

                <div class="collapsible-content" id="content-{index}">
                    <div class="mt-3">
                        <p class="text-sm text-gray-500 mb-2">
                            <i class="fas fa-code mr-1"></i>{self._t('detected_pattern')}:
                        </p>
                        <div class="code-block">
                            {self._escape_html(pattern)}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        """

    def _render_recommendation_section(self, risk_level: str, risk_config: Dict[str, str]) -> str:
        """渲染建议部分"""
        recommendations = {
            'CRITICAL': self._t('do_not_use'),
            'HIGH': self._t('not_recommended'),
            'MEDIUM': self._t('review_needed'),
            'LOW': self._t('use_with_caution'),
            'SAFE': self._t('safe')
        }

        recommendation = recommendations.get(risk_level, 'UNKNOWN RISK LEVEL')

        return f"""
        <div class="{risk_config['bg_light']} {risk_config['border_color']} border-t-4 rounded-lg shadow-lg p-6 mt-8">
            <div class="flex items-start">
                <i class="fas {risk_config['icon']} text-4xl {risk_config['text_color']} mr-4 mt-1"></i>
                <div>
                    <h3 class="text-xl font-bold {risk_config['text_color']} mb-2">{self._t('recommendation')}</h3>
                    <p class="text-gray-700 text-lg">{recommendation}</p>
                </div>
            </div>
        </div>
        """

    def _get_interactive_script(self) -> str:
        """获取交互式 JavaScript"""
        return """
        <script>
            function filterFindings(severity) {
                const sections = document.querySelectorAll('.finding-section');
                sections.forEach(section => {
                    if (severity === 'all' || section.dataset.severity === severity) {
                        section.style.display = 'block';
                    } else {
                        section.style.display = 'none';
                    }
                });

                // 更新按钮状态
                document.querySelectorAll('.filter-btn').forEach(btn => {
                    btn.classList.remove('ring-2', 'ring-offset-2', 'ring-blue-500');
                });
                event.target.classList.add('ring-2', 'ring-offset-2', 'ring-blue-500');
            }

            function toggleCollapse(index) {
                const content = document.getElementById('content-' + index);
                const icon = document.getElementById('icon-' + index);

                content.classList.toggle('expanded');
                icon.classList.toggle('fa-chevron-down');
                icon.classList.toggle('fa-chevron-up');
            }
        </script>
        """

    def _group_by_severity(self, findings: list) -> Dict[str, list]:
        """按严重级别分组"""
        grouped = {}
        for finding in findings:
            severity = finding.get('severity', 'INFO')
            if severity not in grouped:
                grouped[severity] = []
            grouped[severity].append(finding)
        return grouped

    def _get_confidence_label(self, confidence: float) -> str:
        """获取置信度标签"""
        if confidence >= 0.9:
            return 'HIGH'
        elif confidence >= 0.7:
            return 'MEDIUM'
        else:
            return 'LOW'

    def _get_confidence_color(self, confidence: float) -> str:
        """获取置信度颜色"""
        if confidence >= 0.9:
            return 'bg-red-100 text-red-700'
        elif confidence >= 0.7:
            return 'bg-yellow-100 text-yellow-700'
        else:
            return 'bg-blue-100 text-blue-700'

    def _escape_html(self, text: str) -> str:
        """转义 HTML 特殊字符"""
        return (text.replace('&', '&amp;')
                    .replace('<', '&lt;')
                    .replace('>', '&gt;')
                    .replace('"', '&quot;')
                    .replace("'", '&#x27;'))
